version: "3"

services:
  app:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app
    networks:
      - app-network
    expose:
      - "9090"
    volumes:
      - ./logs:/logs
      - ./public/*:/app/public/

  nginx:
    build:
      context: .
      dockerfile: "./build/config/nginx/Dockerfile"
    container_name: nginx
    networks:
      - app-network
    ports:
      - "90:90"
    depends_on:
      - app
    volumes:
      - ./build/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./remove_cache.sh:/remove_cache.sh

networks:
  app-network:
